[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016"
]
default = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[advisories]
ignore = [
    "RUSTSEC-2020-0071", # time crate segfault. We only use it in tests.
]