[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "ISC",
]

[[licenses.exceptions]]
allow = ["BSD-3-Clause"]
name = "bindgen"

[bans]
multiple-versions = "warn"
wildcards = "deny"
